name: 2470FinalEnv
channels:
  - defaults
dependencies:
  - python==3.8.12
  - pip==21.3.1
  pip:
    - gdown==4.6.0
    - keras==2.11.0
    - keras_vggface==0.6
    - matplotlib==3.5.2
    - nltk==3.7
    - numpy==1.21.5
    - opencv_python
    - pandas==1.4.4
    - tensorflow==2.11.0
    - torch==1.13.0
    - transformers==4.23.1
    - evaluate==0.3.0
